#!/usr/bin/env python

from __future__ import division, print_function

from os.path import basename
from sys import argv as sys_argv, exit as sys_exit, stderr

from idepi._scripts import *
from idepi._scripts import __all__ as programs


def main(argv=sys_argv):
    argv[0] = basename(argv[0])
    name = argv[0]

    try:
        argv[0] = ' '.join(argv[:2])
        progname = argv.pop(1)
        assert(progname in programs)
    except:
        print('usage: %s [%s] ARGS' % (name, '|'.join(programs)), file=stderr)
        return -1

    return globals()[progname](argv)


if __name__ == '__main__':
    sys_exit(main())
