#!/usr/bin/env python

from __future__ import division, print_function

from argparse import ArgumentParser
from sys import argv as sys_argv, exit as sys_exit

from idepi.scripts import *
from idepi.scripts import __all__ as scripts


def main(args=None):
    if args is None:
        args = sys_argv[1:]

    parser = ArgumentParser(description='IDentify EPItopes')
    subparsers = parser.add_subparsers(
        title='subcommands',
        description='valid subcommands',
        help='additional help'
    )
    for script in scripts:
        p = subparsers.add_parser(script, add_help=False)
        p.set_defaults(script=globals()[script])

    ns, args = parser.parse_known_args()

    ns.script(args)

    return 0


if __name__ == '__main__':
    sys_exit(main())
