#!/usr/bin/env python

from __future__ import division, print_function

from argparse import ArgumentParser
from sys import argv, exit, stderr

from idepi.scripts import *
from idepi.scripts import __all__ as scripts


def main(args=None):
    if args is None:
        args = argv[1:]

    parser = ArgumentParser(description='IDentify EPItopes')
    subparsers = parser.add_subparsers(
        title='subcommands',
        description='valid subcommands',
        help='additional help'
    )
    for script in scripts:
        p = subparsers.add_parser(script, add_help=False)
        p.set_defaults(script=globals()[script])

    ns, args = parser.parse_known_args()

    ns.script(args)

    return 0


if __name__ == '__main__':
    try:
        exit(main())
    except RuntimeError as e:
        print('ERROR:', str(e), file=stderr)
        exit(-1)
